added flake for Nix and dependency info
Kirottu/watershot pull request #5
Opened 2023-05-08 23:33 UTC by borgmanJeremy

I added a flake for nix users to make development easier. While working on that I also added some info to the README that fixes build issues on a clean Linux install.

Amazing project btw, I've been pondering a rewrite of flameshot in Rust. Do you intend to add annotation features and other features from flameshot?

2023-05-09 09:37 UTC, Kirottu commented
Annotations are not a thing I personally use, but I do see the value in them. Implementing them is definitely possible, but not a big priority for me right now.

2023-05-10 09:59 UTC, Kirottu commented on .envrc
If this isn't strictly required I'd prefer to not have it in the repo

2023-05-10 22:57 UTC, Lord-Valen requested changes

2023-05-10 22:57 UTC, Lord-Valen commented on .envrc
This is just a convenience for nix contributors.

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
> +      devShell = forAllSystems (system: self.devShells.${system}.default);
```suggestion
```
This is redundant and deprecated. Just use `devShells.*.default`.

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
> +
No package? It would be nice..

Right now watershot is using a particular rev of smithay-client-toolkit which requires us to specify a hash. @Kirottu If we could move up to a point release (0.17.0) that would make a package definition simpler to maintain. I've been trying to update and refactor but I seem to have borked it in the process (I'm not well versed in rust yet).

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
Have you considered using https://github.com/divnix/std?

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
> +  outputs = { self, nixpkgs, ... }:
```suggestion
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };
  
  outputs = { self, nixpkgs, ... }:
```
Let's define the nixpkgs input explicitly.

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
Can we add a flake.lock?

2023-05-10 22:57 UTC, Lord-Valen commented on flake.nix
> +
Note: if we add a package definition, we should also add nix instructions.

2023-05-10 23:03 UTC, Lord-Valen commented on .envrc
I believe the particular use case here is to make the rust tooling available to an IDE, as he specified the tools as being a part of the devshell.

2023-05-10 23:04 UTC, borgmanJeremy commented
@Lord-Valen im a nix noob so if you know what you are doing I’m happy close this in favor or a PR you submit. Thanks for the feedback in either case as it’s a great way to learn.

2023-05-10 23:15 UTC, Lord-Valen commented
> @Lord-Valen im a nix noob so if you know what you are doing I’m happy close this in favor or a PR you submit. Thanks for the feedback in either case as it’s a great way to learn.

No worries! :yum: Reviews are always a good opportunity to learn! I do have a flake setup (which works with the latest revision). I was just worried about maintenance concerning smithay-client-toolkit (particularly the prospect of updating the hash). I suppose I'll throw up a PR to supersede this and leave the thinking regarding smithay-client-toolkit 0.17.0 to @Kirottu.

2023-05-11 04:06 UTC, Kirottu commented
Yeah I do agree that using a proper point release of SCTK would be ideal, the git rev was originally used due to how far it had progressed from the last release.

I will close this PR now and will reply in #9 when I have progress.

2023-05-11 04:06 UTC, closed without merging